AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ColorSplashColorDetector

  Sample SAM Template for ColorSplashColorDetector

Globals:
  Function:
    Timeout: 3

Resources:
  ColorSplashPhotoDetectorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.8
      MemorySize: 512
      Timeout: 500
      Description: A Lambda function that returns a list of ids.
      FunctionName: ColorSplashPhotoDetector
      Policies:
        - AWSLambdaBasicExecutionRole
      Layers:
        - arn:aws:lambda:us-west-1:325793726646:layer:AWSLambda-Python38-SciPy1x:29
      Events:
        ColorSplashPhotoDetectorApi:
          Type: Api
          Properties:
            Path: /getIds
            Method: get
Outputs:
  ColorSplashPhotoDetectorApi:
    Description: "API Gateway endpoint URL for Prod stage for ColorSplashPhotoDetector function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getIds/"
  ColorSplashPhotoDetectorFunction:
    Description: "ColorSplashPhotoDetector Lambda Function ARN"
    Value: !GetAtt ColorSplashPhotoDetectorFunction.Arn
  ColorSplashPhotoDetectorFunctionIamRole:
    Description: "Implicit IAM Role created for ColorSplashPhotoDetector function"
    Value: !GetAtt ColorSplashPhotoDetectorFunctionRole.Arn
